/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pratice;

/**
 *
 * @author Gladwin
 */
public class CheckBox extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CheckBox() {
        initComponents();
    }
    private String HI = "hi";
    private String NO = "no";
    private String YES = "yes";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hichk1 = new javax.swing.JCheckBox();
        Nochk2 = new javax.swing.JCheckBox();
        Yeschk3 = new javax.swing.JCheckBox();
        Resultlbl = new javax.swing.JLabel();
        clickbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Hichk1.setText("jCheckBox1");

        Nochk2.setText("jCheckBox2");

        Yeschk3.setText("jCheckBox3");

        Resultlbl.setText("sdfvsdfg");
        Resultlbl.setToolTipText("");

        clickbtn.setText("Submit");
        clickbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hichk1)
                            .addComponent(Yeschk3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nochk2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(Resultlbl)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clickbtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Hichk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nochk2)
                    .addComponent(Resultlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Yeschk3)
                .addGap(31, 31, 31)
                .addComponent(clickbtn)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickbtnActionPerformed
        // TODO add your handling code here:
        if (Hichk1.isSelected() && Nochk2.isSelected() && Yeschk3.isSelected()) {
            Resultlbl.setText(HI + " " + YES + " " + NO);
        } else if (Hichk1.isSelected() && Yeschk3.isSelected()) {
            Resultlbl.setText(HI + " " + YES);
        } else if (Nochk2.isSelected() && Yeschk3.isSelected()) {
            Resultlbl.setText(NO + " " + YES);
        } else if (Hichk1.isSelected() && Nochk2.isSelected()) {
            Resultlbl.setText(HI + " " + NO);
        } else if (Yeschk3.isSelected()) {
            Resultlbl.setText(YES);
        } else if (Nochk2.isSelected()) {
            Resultlbl.setText(NO);
        } else {
            Resultlbl.setText(HI);
        }


    }//GEN-LAST:event_clickbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Hichk1;
    private javax.swing.JCheckBox Nochk2;
    private javax.swing.JLabel Resultlbl;
    private javax.swing.JCheckBox Yeschk3;
    private javax.swing.JButton clickbtn;
    // End of variables declaration//GEN-END:variables
}
