/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pratice;
import pratice.practice1;
/**
 *
 * @author Gladwin
 */
public class pratice1a extends javax.swing.JFrame {
private practice1 practice;
    /**
     * Creates new form pratice1a
     */
    public pratice1a() {
        initComponents();
         practice= new practice1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayGroup = new javax.swing.ButtonGroup();
        lblchild = new javax.swing.JLabel();
        btnchild = new javax.swing.JButton();
        rdocorrect = new javax.swing.JRadioButton();
        rdoincorrect = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblchild.setText("Result");

        btnchild.setText("Hide Me");
        btnchild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchildActionPerformed(evt);
            }
        });

        rdocorrect.setText("Correct");
        rdocorrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdocorrectActionPerformed(evt);
            }
        });

        rdoincorrect.setText("Incorrect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lblchild))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdocorrect)
                            .addComponent(btnchild)
                            .addComponent(rdoincorrect))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblchild)
                .addGap(33, 33, 33)
                .addComponent(btnchild)
                .addGap(18, 18, 18)
                .addComponent(rdocorrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoincorrect)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchildActionPerformed
        // TODO add your handling code here:
        practice.setVisible(true);
         //this.setVisible(false);
               
        if (rdocorrect.isSelected()) {
            practice.setLblParent("Correct");
        
        } else {
           practice.setLblParent("InCorrect");
        }

         
    }//GEN-LAST:event_btnchildActionPerformed

    private void rdocorrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdocorrectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdocorrectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pratice1a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pratice1a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pratice1a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pratice1a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pratice1a().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DisplayGroup;
    private javax.swing.JButton btnchild;
    public javax.swing.JLabel lblchild;
    private javax.swing.JRadioButton rdocorrect;
    private javax.swing.JRadioButton rdoincorrect;
    // End of variables declaration//GEN-END:variables
}
