/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstgui;

import java.text.DecimalFormat;

/**
 *
 * @author Gladwin
 */
public class TemperatureConverter extends javax.swing.JFrame {

    /**
     * Creates new form TemperatureConverter
     */
    public TemperatureConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConvertTemperature = new javax.swing.ButtonGroup();
        lbl1Temperature = new javax.swing.JLabel();
        txt1input = new javax.swing.JTextField();
        rdoFahrenheit = new javax.swing.JRadioButton();
        rdoCelsius = new javax.swing.JRadioButton();
        lbl2ConvertFahrenheit = new javax.swing.JLabel();
        lbl3ConvertCelsius = new javax.swing.JLabel();
        btnConvert = new javax.swing.JButton();
        lbl4Result = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        txt2output = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl1Temperature.setText("Enter Temperature");

        ConvertTemperature.add(rdoFahrenheit);
        rdoFahrenheit.setSelected(true);
        rdoFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFahrenheitActionPerformed(evt);
            }
        });

        ConvertTemperature.add(rdoCelsius);

        lbl2ConvertFahrenheit.setText("Convert to Fahrenheit");

        lbl3ConvertCelsius.setText("Convert to Celsius");

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        lbl4Result.setText("Result");

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl1Temperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl2ConvertFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lbl3ConvertCelsius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbl4Result)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuit)
                    .addComponent(btnConvert)
                    .addComponent(rdoCelsius)
                    .addComponent(rdoFahrenheit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt2output, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addComponent(txt1input, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1Temperature)
                    .addComponent(txt1input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoFahrenheit)
                    .addComponent(lbl2ConvertFahrenheit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCelsius)
                    .addComponent(lbl3ConvertCelsius))
                .addGap(18, 18, 18)
                .addComponent(btnConvert)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl4Result)
                    .addComponent(txt2output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnQuit)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
//         int tempFahrenheit = (int)((Double.parseDouble(txt1input.getText())) * 1.8 + 32);
//         int tempCelsius = (int)(((Double.parseDouble(txt1input.getText()) -32) * 0.55));

         Double tempFahrenheit = ((Double.parseDouble(txt1input.getText())) * 1.8 + 32);
         Double tempCelsius = (((Double.parseDouble(txt1input.getText()) -32) * 0.55));
         String roundedAnswer1 = String.format("%.2f",tempFahrenheit);
         String roundedAnswer2 = String.format("%.2f",tempCelsius);
                 
         if (rdoFahrenheit.isSelected()) {
            txt2output.setText(roundedAnswer1 +" F");
            //txt2output.setText(tempFahrenheit + " F");
         }else {
              txt2output.setText(roundedAnswer2 +" C");
              //txt2output.setText(tempCelsius + " C");
            
            
        // TODO Auto-generated method stuif (hellordo1.isSelected()) {
         
         }
    }//GEN-LAST:event_btnConvertActionPerformed

    private void rdoFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoFahrenheitActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureConverter().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ConvertTemperature;
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel lbl1Temperature;
    private javax.swing.JLabel lbl2ConvertFahrenheit;
    private javax.swing.JLabel lbl3ConvertCelsius;
    private javax.swing.JLabel lbl4Result;
    private javax.swing.JRadioButton rdoCelsius;
    private javax.swing.JRadioButton rdoFahrenheit;
    private javax.swing.JTextField txt1input;
    private javax.swing.JTextField txt2output;
    // End of variables declaration//GEN-END:variables
}
